name: Build and Attach Release Binaries

on:
  release:
    types:
      - published

# Add concurrency control
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-attach:
    name: Build and Attach Release Binaries
    runs-on: ubuntu-latest
    timeout-minutes: 10 # Add timeout for the job

    # Add explicit permissions
    permissions:
      contents: write # Needed to upload release assets

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Go
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22.5" # Match the version in go.mod
          cache: true # Enable Go dependency caching

      # Install dependencies (runs only if cache missed or go.sum changed)
      - name: Install dependencies
        run: go mod tidy

      # Build all binaries
      - name: Build all binaries
        run: make build-all

      # Upload release assets - Linux
      - name: Upload Linux AMD64 binary
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./vantage-mcp-server-linux-amd64
          asset_name: vantage-mcp-server-linux-amd64
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Linux ARM64 binary
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./vantage-mcp-server-linux-arm64
          asset_name: vantage-mcp-server-linux-arm64
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Upload release assets - macOS
      - name: Upload macOS ARM64 binary
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./vantage-mcp-server-macos-arm64
          asset_name: vantage-mcp-server-macos-arm64
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Upload release assets - Windows
      - name: Upload Windows AMD64 binary
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./vantage-mcp-server-windows-amd64.exe
          asset_name: vantage-mcp-server-windows-amd64.exe
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Windows ARM64 binary
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./vantage-mcp-server-windows-arm64.exe
          asset_name: vantage-mcp-server-windows-arm64.exe
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}